#!/bin/bash
#
# This is a script that collects the CITA runtime environment and error logs.

CITA_DIR="$1"
LOG_COUNT=200
CITA_INFO_DIR="/tmp/cita_info"
mkdir -p ${CITA_INFO_DIR}

CITA_PROCESS="cita-auth
cita-bft
cita-chain
cita-executor
cita-forever
cita-jsonrpc
cita-network
"

cita_info(){
  echo -e "\e[1;32m CITA process info \e[0m" >> ${CITA_INFO_DIR}/cita_info.txt
  ps -ef | grep -E "cita-|rabbitmq" |grep -v grep |wc -l  >> ${CITA_INFO_DIR}/cita_info.txt
  ps -ef | grep -E "cita-|rabbitmq" |grep -v grep >> ${CITA_INFO_DIR}/cita_info.txt

  echo -e "\e[1;32m Memory info \e[0m" >> ${CITA_INFO_DIR}/cita_info.txt
  free -h >> ${CITA_INFO_DIR}/cita_info.txt

  echo -e "\e[1;32m Disk info \e[0m" >> ${CITA_INFO_DIR}/cita_info.txt
  df -h >> ${CITA_INFO_DIR}/cita_info.txt

  echo -e "\e[1;32m Operating system info \e[0m" >> ${CITA_INFO_DIR}/cita_info.txt
  lsb_release -a  >> ${CITA_INFO_DIR}/cita_info.txt

  echo -e "\e[1;32m CPU info \e[0m" >> ${CITA_INFO_DIR}/cita_info.txt
  cpu_core=`grep 'core id' /proc/cpuinfo |wc -l`
  echo "cpu_core:  ${cpu_core}"  >> ${CITA_INFO_DIR}/cita_info.txt
  top -n 1 >> ${CITA_INFO_DIR}/cita_info.txt
  echo "#######The CPU uses the top 50 processes#######" >> ${CITA_INFO_DIR}/cita_info.txt
  ps  -eo user,pid,ppid,tid,time,%cpu,cmd |sort -k 6 -r |head -50 >> ${CITA_INFO_DIR}/cita_info.txt

  node_list=`find ./ -name "network.toml" | awk -F "/" '{print $2"/"$3 }' | grep -v template`
  for node in $node_list; do
    i=`echo ${node} |awk -F ":" '{print $NF}'`
    mkdir -p ${CITA_INFO_DIR}/${i}/logs
    for z in ${CITA_PROCESS}; do
      cp -rp ${i}/*.toml ${CITA_INFO_DIR}/${i}/
      cp -rp ${i}/.env ${CITA_INFO_DIR}/${i}/
      tail -n ${LOG_COUNT} ${i}/logs/${z}.log > ${CITA_INFO_DIR}/${i}/logs/${z}.log
    done
  done

  cd /tmp/
  tar czf cita_info.tar.gz cita_info
  echo -e " \e[1;32m ##### Information collection is complete. . . ##### \e[0m"
  echo -e " \e[1;32m Please submit the /tmp/cita_info.tar.gz file to the administrator to help troubleshoot the issue. \e[0m"
}

execute (){
  if [ -d "$CITA_DIR" ] && echo "${LOG_COUNT}"| [ -n "`sed -n '/^[0-9][0-9]*$/p'`" ]; then
    cd $CITA_DIR
    cita_info
  else
    echo -e "\e[1;31m The entered directory ${CITA_DIR} does not exist or the number of logs ${LOG_COUNT} is incorrect. Please check. \e[0m"
    usage
  fi
}

usage(){
  echo "      usage: $1 CITA DIR"
  echo "      By default, 200 lines of logs are collected. For the number of custom logs, please fill in the number after the script."
  echo "      Please fill in the CITA real deployment directory after the script. "
  echo "      ./cita-op-helper /data/cita_sm2_sm3"
  echo "      ./cita-op-helper /data/cita_sm2_sm3 500"
}

if [ $# -lt 1 ]; then
  usage
elif [ $# -ge 2 ]; then
  LOG_COUNT="$2"
  execute
else
  execute
fi
