#!/bin/bash

CITA_DIR="$1"

LOG_COUNT=200

CITA_INFO_DIR="/tmp/cita_info"
mkdir -p ${CITA_INFO_DIR}

cita_info(){
	echo -e "\e[1;32m CITA process information \e[0m" >> ${CITA_INFO_DIR}/cita_info.txt
	ps -ef | grep -E "cita-|rabbitmq" |grep -v grep |wc -l  >> ${CITA_INFO_DIR}/cita_info.txt
	ps -ef | grep -E "cita-|rabbitmq" |grep -v grep >> ${CITA_INFO_DIR}/cita_info.txt

	echo -e "\e[1;32m Memory info \e[0m" >> ${CITA_INFO_DIR}/cita_info.txt
	free -h >> ${CITA_INFO_DIR}/cita_info.txt

	echo -e "\e[1;32m Disk info \e[0m" >> ${CITA_INFO_DIR}/cita_info.txt
	df -h >> ${CITA_INFO_DIR}/cita_info.txt

	echo -e "\e[1;32m Operating system info \e[0m" >> ${CITA_INFO_DIR}/cita_info.txt
	lsb_release -a  >> ${CITA_INFO_DIR}/cita_info.txt

	node_list=`find ./ -name "network.toml" | awk -F "/" '{print $2"/"$3 }' | grep -v template`
	for i in $node_list:
		do
		i=`echo ${i} |awk -F ":" '{print $1}'`
		mkdir -p ${CITA_INFO_DIR}/${i}/logs
		tail -n ${LOG_COUNT} ${i}/logs/cita-auth.log > ${CITA_INFO_DIR}/${i}/logs/cita-auth.log
		tail -n ${LOG_COUNT} ${i}/logs/cita-bft.log > ${CITA_INFO_DIR}/${i}/logs/cita-bft.log
		tail -n ${LOG_COUNT} ${i}/logs/cita-chain.log > ${CITA_INFO_DIR}/${i}/logs/cita-chain.log
		tail -n ${LOG_COUNT} ${i}/logs/cita-executor.log > ${CITA_INFO_DIR}/${i}/logs/cita-executor.log
		tail -n ${LOG_COUNT} ${i}/logs/cita-forever.log > ${CITA_INFO_DIR}/${i}/logs/cita-forever.log
		tail -n ${LOG_COUNT} ${i}/logs/cita-jsonrpc.log > ${CITA_INFO_DIR}/${i}/logs/cita-jsonrpc.log
		tail -n ${LOG_COUNT} ${i}/logs/cita-network.log > ${CITA_INFO_DIR}/${i}/logs/cita-network.log
		cp -rp ${i}/*.toml ${CITA_INFO_DIR}/${i}/
	done

	cd /tmp/
	tar czf cita_info.tar.gz cita_info
	echo -e " \e[1;32m ##### Information collection is complete. . . ##### \e[0m"
	echo -e " \e[1;32m Please submit the /tmp/cita_info.tar.gz file to the administrator to help troubleshoot the issue. \e[0m"
}

execute (){
    if [ -d "$CITA_DIR" ] && echo "${LOG_COUNT}"| [ -n "`sed -n '/^[0-9][0-9]*$/p'`" ]
        then
        cd $CITA_DIR
        if [  -f "./env.sh" ]; then
            echo -e "\e[1;32m CITA software version number \e[0m" > ${CITA_INFO_DIR}/cita_info.txt
            ./env.sh ./bin/cita-jsonrpc --version | grep JsonRpc |awk '{print $2}' >> ${CITA_INFO_DIR}/cita_info.txt
            cita_info

	    elif [  -f "bin/cita-env" ]; then
            echo -e "\e[1;32m CITA software version number \e[0m" > ${CITA_INFO_DIR}/cita_info.txt
            ./bin/cita-env ./bin/cita-jsonrpc --version | grep JsonRpc |awk '{print $2}' >> ${CITA_INFO_DIR}/cita_info.txt
	        cita_info

	    else
			echo -e "\e[1;31m The ${CITA_DIR} path is not the deployment directory of CITA. Please verify the path. \e[0m"
			usage
        fi

    else
	    echo -e "\e[1;31m The entered directory ${CITA_DIR} does not exist or the number of logs ${LOG_COUNT} is incorrect. Please check. \e[0m"
	    usage
    fi
}

usage(){
    echo "      usage: $0 CITA DIR"
	echo "      By default, 200 lines of logs are collected. For the number of custom logs, please fill in the number after the script."
    echo "      Please fill in the CITA real deployment directory after the script. "
    echo "      ./cita-op-helper /data/cita_secp256k1_sha3"
    echo "      ./cita-op-helper /data/cita_secp256k1_sha3 500"

}

if [ $# -lt 1 ];
    then
    usage
elif [ $# -ge 2 ];
    then
    LOG_COUNT="$2"
    execute
else
    execute
fi
